name: prova
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  build_runner: ^2.4.6
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_mobx: ^2.1.1
  flutter_modular: ^6.3.2
  http_mock_adapter: ^0.6.0
  mobx: ^2.2.1
  mobx_codegen: ^2.4.0
  mocktail: ^1.0.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
